Try installing cairo to fix error
Think caused by ComplexHeatmap

  Error: processing vignette 'manuscript_differential_transcript_abundance.Rmd' failed with diagnostics:
   package or namespace load failed for 'tidyHeatmap':
    .onLoad failed in loadNamespace() for 'Cairo', details:
     call: dyn.load(file, DLLpath = DLLpath, ...)
     error: unable to load shared object '/Users/runner/work/_temp/Library/Cairo/libs/Cairo.so':
     dlopen(/Users/runner/work/_temp/Library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
     Referenced from: /Users/runner/work/_temp/Library/Cairo/libs/Cairo.so
     Reason: image not found